### ISSUE TITLE
Add Media Playback

### ISSUE THREAD

**Issue by BrianAker** [stephack/ABC#2]
Could you please add support for "Media Playback" alongside "Music Player"?

Thanks!

**Comment by stephack** [comment]
Unfortunately I no longer use ST for my home automation needs and I'm not very active in that community anymore. There won't be any further updates to this app.
I'm not sure what you mean by "Media Playback" but there should already be separate options for Play/Pause, Next Track, Mute, etc.
Any assistance you need with this app would be better served in the ST forums where existing users can assist.
